version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=todoapp
    ports:
      - 3306:3306
    volumes:
      - todoapp-mysql-data:/var/lib/mysql
      - todoapp-mysql-config:/etc/mysql
  node_backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DBNAME: todoapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
    volumes:
      - ./:/nestjs_todoapp
    ports:
      - "3030:3030"
    depends_on:
      - db

volumes:
  todoapp-mysql-data:
  todoapp-mysql-config: