version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=todoapp
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - todoapp-mysql-data:/var/lib/mysql
      - todoapp-mysql-config:/etc/mysql

volumes:
  todoapp-mysql-data:
  todoapp-mysql-config: